import type { BasketModeConfig } from './types';
import { CORE_ANCHORS } from './coreAnchors';

export const campaignBrainMode: BasketModeConfig = {
  id: 'campaign_brain',
  label: 'Campaign Brain',
  tagline: 'Transform research into multi-channel storytelling.',
  description:
    'Designed for marketing teams that need cohesive campaigns. Campaign Brain consumes existing substrate (especially Product Brain anchors) to produce briefs, channel matrices, and prompt libraries.',
  onboarding: {
    headline: 'Collect signal, align messaging, launch coherently.',
    steps: [
      {
        id: 'capture_inputs',
        title: 'Capture audience research',
        description: 'Upload call notes, surveys, and briefs so Yarnnn can extract positioning blocks.',
        cta: { label: 'Add Research', href: '#add-memory' },
      },
      {
        id: 'shape_story',
        title: 'Approve messaging substrate',
        description: 'Review hooks, offers, and voice anchors to keep messaging canon-pure.',
        cta: { label: 'Review Blocks', href: '/building-blocks' },
      },
      {
        id: 'ship_campaign',
        title: 'Compose the campaign kit',
        description: 'Generate the campaign brief and channel matrix, then trigger reflections for optimisation cues.',
        cta: { label: 'Open Documents', href: '/documents' },
      },
    ],
    completion: 'When campaign brief, channel matrix, and prompt library exist with references to core anchors, onboarding is complete.',
  },
  anchors: {
    core: CORE_ANCHORS,
    brain: [
      {
        id: 'campaign_objective',
        label: 'Campaign Objective',
        scope: 'brain',
        substrateType: 'block',
        description: 'The outcome this campaign must achieve and how it ladders to success metrics.',
        acceptanceCriteria: 'References success metrics, defines timeframe, and highlights primary audience segment.',
        required: true,
        dependsOn: ['success_metrics', 'core_customer'],
      },
      {
        id: 'audience_tension',
        label: 'Audience Tension',
        scope: 'brain',
        substrateType: 'block',
        description: 'What emotional or practical tension motivates the audience.',
        acceptanceCriteria: 'Captures current state vs desired state with supporting evidence.',
        required: true,
        dependsOn: ['core_problem', 'core_customer'],
      },
      {
        id: 'core_offer',
        label: 'Core Offer',
        scope: 'brain',
        substrateType: 'block',
        description: 'The promise we make to resolve the tension. Ties directly to product solution anchors.',
        acceptanceCriteria: 'Summarises benefit, proof, and CTA. References core_solution anchor if present.',
        required: true,
        dependsOn: ['core_solution'],
      },
      {
        id: 'brand_voice',
        label: 'Brand Voice & Guardrails',
        scope: 'brain',
        substrateType: 'context_item',
        description: 'Tone, vocabulary, and do/don’t guidelines for copy.',
        acceptanceCriteria: 'Lists descriptors (e.g., Bold, Warm), forbidden phrases, and reference campaigns.',
        required: true,
      },
      {
        id: 'channel_plan',
        label: 'Channel Plan',
        scope: 'brain',
        substrateType: 'context_item',
        description: 'Priority channels with goal, budget, and hero asset.',
        acceptanceCriteria: 'Each channel entry specifies objective, key metric, cadence, and owner.',
        required: true,
      },
      {
        id: 'creative_hook',
        label: 'Creative Hook',
        scope: 'brain',
        substrateType: 'block',
        description: 'Headline or hook aligned to a channel and offer.',
        acceptanceCriteria: 'Includes hook text, target channel, linked offer/benefit, and proof point.',
        required: true,
        dependsOn: ['core_offer', 'channel_plan'],
      },
      {
        id: 'measurement_plan',
        label: 'Measurement Plan',
        scope: 'brain',
        substrateType: 'context_item',
        description: 'Defines how success will be tracked per channel.',
        acceptanceCriteria: 'Links channel to success metrics, defines leading/lagging indicators, and review cadence.',
        required: false,
        dependsOn: ['channel_plan', 'success_metrics'],
      },
    ],
  },
  captureRecipes: [
    {
      id: 'research-dump',
      title: 'Audience Research Dump',
      description: 'Upload voice-of-customer data to seed tensions and offers.',
      captureType: 'file_upload',
      intentMetadata: { category: 'audience_research' },
      anchorRefs: ['audience_tension'],
    },
    {
      id: 'offer-workshop',
      title: 'Offer Workshop',
      description: 'Inline helper to summarise offer, proof, and CTA.',
      captureType: 'inline_block',
      prompt: 'Offer · Benefit · Proof · Primary CTA.',
      anchorRefs: ['core_offer'],
    },
    {
      id: 'voice-guardrails',
      title: 'Voice & Guardrails',
      description: 'Capture tone, examples, and guardrails to keep messaging consistent.',
      captureType: 'inline_context',
      prompt: 'Voice descriptors · sample phrases · forbidden phrases · competitor references.',
      anchorRefs: ['brand_voice'],
    },
    {
      id: 'channel-planner',
      title: 'Channel Planner',
      description: 'Define channels, hero asset, and budget/emphasis.',
      captureType: 'inline_context',
      prompt: 'Channel · objective · hero asset · key metric · budget or emphasis.',
      anchorRefs: ['channel_plan'],
    },
    {
      id: 'hook-sprint',
      title: 'Creative Hook Sprint',
      description: 'Brainstorm hooks/headlines tied to the offer and channel.',
      captureType: 'inline_block',
      prompt: 'Hook/headline · target channel · referenced offer · proof/credential.',
      anchorRefs: ['creative_hook'],
    },
    {
      id: 'measurement-outline',
      title: 'Measurement Outline',
      description: 'Capture leading and lagging indicators per channel.',
      captureType: 'inline_context',
      prompt: 'Channel · leading indicator · lagging indicator · review cadence.',
      anchorRefs: ['measurement_plan'],
    },
  ],
  deliverables: [
    {
      id: 'campaign_brief',
      title: 'Campaign Brief',
      description: 'Narrative brief tying audience insight, offer, and voice into a cohesive plan.',
      composeIntent: 'campaign_brief_v1',
      requiredAnchors: ['core_problem', 'core_customer', 'campaign_objective', 'audience_tension', 'core_offer', 'brand_voice'],
      optionalAnchors: ['customer_insights', 'measurement_plan'],
    },
    {
      id: 'channel_matrix',
      title: 'Channel Matrix',
      description: 'Mode-aware matrix mapping hooks and assets across priority channels.',
      composeIntent: 'campaign_channel_matrix_v1',
      requiredAnchors: ['channel_plan', 'creative_hook', 'measurement_plan'],
    },
    {
      id: 'prompt_library',
      title: 'Prompt Library',
      description: 'Context-rich prompts for creative execution anchored to approved substrate.',
      composeIntent: 'campaign_prompt_library_v1',
      requiredAnchors: ['brand_voice', 'creative_hook', 'core_offer'],
    },
  ],
  progress: {
    checklist: [
      {
        id: 'core-synced',
        label: 'Core truths synced',
        description: 'Campaign anchors reference core problem, customer, and vision.',
        requiredAnchors: ['core_problem', 'core_customer', 'product_vision'],
      },
      {
        id: 'offer-ready',
        label: 'Offer & tension defined',
        description: 'Audience tension and core offer anchors approved.',
        requiredAnchors: ['audience_tension', 'core_offer'],
      },
      {
        id: 'channels-lined',
        label: 'Channel plan & hooks captured',
        description: 'Channel plan, creative hooks, and voice anchors populated.',
        requiredAnchors: ['channel_plan', 'creative_hook', 'brand_voice'],
        minCounts: { creative_hook: 3 },
      },
    ],
  },
};
