'use client';

interface AgentAttributionProps {
  agentSource?: string;
  createdByAgent?: boolean;
  confidence?: number;
  timestamp?: string;
  className?: string;
}

export function AgentAttribution({ 
  agentSource, 
  createdByAgent, 
  confidence,
  timestamp,
  className = ''
}: AgentAttributionProps) {
  if (!createdByAgent && !agentSource) return null;
  
  const formatTimestamp = (ts: string) => {
    try {
      return new Date(ts).toLocaleTimeString();
    } catch {
      return '';
    }
  };

  return (
    <div 
      className={`flex items-center space-x-2 text-xs text-gray-500 mt-2 ${className}`}
      data-testid="agent-attribution"
    >
      <span className="text-blue-500">🤖</span>
      <span>
        Generated by <span className="font-medium">{agentSource || 'AI Agent'}</span>
        {confidence && confidence > 0 && (
          <span className="ml-1 text-gray-400">
            ({Math.round(confidence * 100)}% confidence)
          </span>
        )}
      </span>
      {timestamp && (
        <span className="text-gray-400">
          • {formatTimestamp(timestamp)}
        </span>
      )}
    </div>
  );
}