services:
  - type: web
    name: yarnnn-mcp-server
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: BACKEND_URL
        value: https://api.yarnnn.com
      - key: NODE_ENV
        value: production
      - key: MCP_TRANSPORT
        value: http
      - key: PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
