[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rightnow-api"
version = "0.0.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
