name: CI

on:
  push:
    paths:
      - 'api/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'api/**'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: api/src
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-extras --all-packages --group dev
      - name: Run tests
        run: make tests
