name: CI - API Tests

on:
  push:
    paths:
      - 'api/**'
      - 'tests/**'
      - 'setup.py'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'api/**'
      - 'tests/**'
      - 'setup.py'
      - '.github/workflows/ci.yml'

jobs:
  test-api:
    runs-on: ubuntu-latest
    name: Run API Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies + src in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # editable install via setup.py
          pip install pytest

      - name: Run Pytest
        run: pytest -q --tb=short

      # Optional: Add linting step here later if needed
