"use client";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";

export interface Block {
  id: string;
  type: string;
  label: string;
  content: string;
  update_policy: string;
  is_core_block: boolean;
  meta_scope?: string;
}

interface BlockCardProps {
  block: Block;
  onToggleAuto?: (id: string, enable: boolean) => void;
}

export default function BlockCard({ block, onToggleAuto }: BlockCardProps) {
  const scopeStyles: Record<string, string> = {
    basket: "border-blue-300",
    profile: "border-green-300",
    agent: "border-purple-300",
  };

  const scopeTitles: Record<string, string> = {
    basket: "Created from a basket",
    profile: "From profile setup",
    agent: "Generated by agent",
  };

  const scopeIcons: Record<string, string> = {
    basket: "📦",
    profile: "👤",
    agent: "🤖",
  };

  const borderClass = block.meta_scope ? scopeStyles[block.meta_scope] : "";
  const title = block.meta_scope ? scopeTitles[block.meta_scope] : undefined;

  const icon = block.meta_scope ? scopeIcons[block.meta_scope] : null;

  return (
    <Card className={`space-y-2 ${borderClass}`} title={title}>
      <div className="flex justify-between items-center">
        <div className="text-sm font-medium">
          {icon && <span className="mr-1">{icon}</span>}
          {block.label}
          <span className="ml-2 text-xs px-2 py-0.5 bg-primary/10 rounded">
            {block.type}
          </span>
          {block.meta_scope && (
            <span className="ml-2 text-xs px-2 py-0.5 bg-muted rounded border">
              {block.meta_scope}
            </span>
          )}
        </div>
        {onToggleAuto && (
          <Button
            size="sm"
            variant="outline"
            onClick={() => onToggleAuto(block.id, block.update_policy !== "auto")}
          >
            {block.update_policy === "auto" ? "Manual" : "Auto-update"}
          </Button>
        )}
      </div>
      <p className="text-sm text-muted-foreground">
        {block.content.slice(0, 120)}
        {block.content.length > 120 ? "…" : ""}
      </p>
    </Card>
  );
}
